### PR TITLE
Change the property used to aggregate coin bases

### LINKED ISSUE #1: Error loading coins
Hello!
I've found a problem in the `_refreshCoins` function.
As it uses the `aliasTokenSymbol` to make the aggregation of bases it expects that this value is always the same.
I found that it is not true for all coins, see the DASH example: 

    {
      "base": "BTC",
      "standardTokenSymbol": "DASH",
      "displayedTokenSymbol": "DASH",
      "aliasTokenSymbol": "DSH",
      "fullName": "Dash"
    },
    {
      "base": "PLN",
      "standardTokenSymbol": "DASH",
      "displayedTokenSymbol": "DASH",
      "aliasTokenSymbol": "DASH",
      "fullName": "Dash"
    },
    {
      "base": "KRW",
      "standardTokenSymbol": "DASH",
      "displayedTokenSymbol": "DASH",
      "aliasTokenSymbol": "DASH",
      "fullName": "Dash"
    }

### PR DESCRIPTION
**Pull request by johnnyasantoss**
Fixes #1

### CODE REVIEW

**Comment by johnnyasantoss** [comment]
Actually, now using `standardTokenSymbol` it fails for BCH (or BCC in Bittrex)

**Comment by bob6664569** [comment]
Ahah... Sorry about the apps spam, had tested too much of thoses without removing all the webhooks ! Thanks for the PR, seems legit, merging !

**Comment by johnnyasantoss** [comment]
Would be nice if you could release a npm package version with this fix :smile:

**Comment by bob6664569** [comment]
Last version released 👍

**Pull request merged**
