### PR TITLE
Add date and fix buy/sell operation insertion

### LINKED ISSUE #3: addPosition function doesn't have a parameter of date
With this behaviour it is not possible to add historical transactions :confused:

### PR DESCRIPTION
**Pull request by johnnyasantoss**
Fix #3

### CODE REVIEW

**Comment by johnnyasantoss** [comment]
It was fun to reverse engineer the Blockfolio app to find why the buy/sell option wasn't inserting correct :rofl:

**Comment by johnnyasantoss** [comment]
I still need to check and write more tests :)

**Comment by bob6664569** [comment]
The fix for buy/sell was made some days ago.. https://github.com/bob6664569/blockfolio-api-client/commit/72c332daeff0c2af57b8571f671241cbfa17f40a :) And concerning options on this method, everything must be fine on v1.0 (already issued some versions on dev branch / npm @beta tag), check it out !

**Comment by bob6664569** [comment]
Just update the test and I'll merge it anyway, thanks :)

**Comment by johnnyasantoss** [comment]
Awesome! I'll check the beta version later today :)
The beta version has promises already?

**Comment by bob6664569** [comment]
Yes, now fully promisified, maybe some method signatures will change again soon, but that's closer and closer from a proper v1 ! Look at [this example](https://github.com/bob6664569/blockfolio-api-client/tree/develop#examples) (I just updated the documentation for the `addPosition` method yet)

**Comment by bob6664569** [comment]
👍

**Pull request merged**
